extends Node
class_name Alchemy_Enums

enum Metal_Type {PLANETARY, MUNDANE, PRIME, NONE}
enum Metals {LEAD, TIN, IRON, GOLD, COPPER, QUICKSILVER, SILVER}
enum Mundane {ANTIMONY, ARSENIC, BISMUTH, COBALT, MANGANESE, NICKEL, OXYGEN, PHLOGISTON, PHOSPHORUS, PLATINUM, SULFUR, ZINC, NONE }
enum Compounds {ACID, SAL_AMMONIAC, AQUA_FORTIS, AQUA_REGIA, SPIRIT_OF_WINE, AMALGAM, CINNABAR, VINEGAR, VITRIOL, BLACK_SULFER, NONE}
enum Compound_Type {ACID, BASE, ETHANOL, ALLOY, SULFIDE, SULFATE}
enum Elements {FIRE, WATER, AIR, EARTH, NONE}
